Merge dev branch
andriycraft/GreenFrogMCBE pull request #25
Opened 2023-01-04 20:33 UTC by andriycraft

2023-01-04 20:53 UTC, andriy332 requested changes

2023-01-04 20:53 UTC, andriy332 commented on src/chat/Colors.js
> +    // there is no strikethrough because bedrock does not support it
remove

2023-01-04 20:53 UTC, andriy332 commented on src/chat/Colors.js
> +    // there is no underline because bedrock does not support it
remove

2023-01-04 20:53 UTC, andriy332 commented on src/console/Logger.js
> +                break
mabye throw an error or something?

2023-01-04 20:53 UTC, andriy332 commented on src/console/Logger.js
>                  throw new Error(`${lang.invalid}`)
console.log(`${lang.invalid}`)

2023-01-04 20:53 UTC, andriy332 commented on src/player/KickPlayer.js
> +        if (!client) throw new Error("kick(): No client!")
kick(client): No client!

2023-01-04 20:53 UTC, andriy332 commented on src/plugins/Unloader.js
> +            process.exit(config.exitstatuscode) // TODO: Not sure if this is useful (i mean the config for exit status code)
it is

2023-01-04 21:05 UTC, andriycraft commented on src/plugins/Unloader.js
> +            process.exit(config.exitstatuscode) // TODO: Not sure if this is useful (i mean the config for exit status code)
not sure if it is. any examples of usage?

2023-01-04 21:05 UTC, andriycraft commented on src/plugins/Unloader.js
> +                    // TODO: Somehow use await
TODO: Use await

2023-01-04 21:05 UTC, andriycraft commented on src/player/KickPlayer.js
> +    kick(client, reason = 'You were disconnected') {
TODO: Make the default kick reason customizable

2023-01-04 21:05 UTC, andriycraft commented on src/player/KickPlayer.js
> +        if (!client) throw new Error("kick(): No client!")
TODO: Same here

2023-01-04 21:05 UTC, andriycraft commented on src/player/Chatmessage.js
> +        Logger.prototype.log(`(broadcast) ${msg}`)
TODO: Translate to other langs

2023-01-04 21:05 UTC, andriycraft commented on src/player/Chatmessage.js
> +        if (!msg) throw new Error("broadcastMessage(msg): No chat message!");
TODO: Translate to other langs

2023-01-04 21:05 UTC, andriycraft commented on src/player/Chatmessage.js
> +        if (!client) throw new Error("sendmessage(client, msg): No client!")
TODO: Translate to other langs

2023-01-04 21:05 UTC, andriycraft commented on src/player/Chatmessage.js
>      sendMessage(client, msg) {
TODO: Translate to other langs

2023-01-05 18:38 UTC, merged

2023-01-05 18:38 UTC, andriycraft commented
Update finished